from typing import Protocol
from .schema import Hypothesis, Candidate

class ResearchAgent(Protocol):
    def discover(self, context: dict) -> list[Hypothesis]: ...
    def design(self, hypothesis: Hypothesis, context: dict) -> list[Candidate]: ...
    def critique(self, candidate: Candidate, results: dict) -> list[str]: ...
    def decide(self, candidate: Candidate, results: dict) -> str: ...
