from typing import Protocol, Any
import pandas as pd
from .schemas import Hypothesis, StrategyCandidate

class DataProvider(Protocol):
    def fetch_ohlcv(self, symbol: str, timeframe: str, start: str, end: str) -> pd.DataFrame: ...

class AgentRuntime(Protocol):
    def discover(self, context: dict[str, Any]) -> list[Hypothesis]: ...
    def build(self, hypothesis: Hypothesis, context: dict[str, Any]) -> list[StrategyCandidate]: ...
    def analyze(self, results: list[dict[str, Any]], context: dict[str, Any]) -> dict[str, Any]: ...

class BacktestEngine(Protocol):
    def run(self, data: pd.DataFrame, signal: pd.Series, context: dict[str, Any]) -> Any: ...
